### ISSUE TITLE
Getting ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by montanaflynn** [l1j-en/classic#52]
With the 363 branch I get this error, any idea why it could be? I'm using openjdk 11.

```
server_1  | 2020.11.06 08:22:01 L1WorldMap.<init> INFO: Loading Map...
server_1  | 2020.11.06 08:22:01 MapsTable.loadMapsFromDatabase INFO: Maps 545
server_1  | 2020.11.06 08:22:01 L1WorldMap.<init> SEVERE: Index 128 out of bounds for length 128
server_1  | 2020.11.06 08:22:01 java.lang.ArrayIndexOutOfBoundsException: Index 128 out of bounds for length 128
server_1  | 	at l1j.server.server.model.map.TextMapReader.read(TextMapReader.java:87)
server_1  | 	at l1j.server.server.model.map.TextMapReader.read(TextMapReader.java:113)
server_1  | 	at l1j.server.server.model.map.TextMapReader.read(TextMapReader.java:149)
server_1  | 	at l1j.server.server.model.map.L1WorldMap.<init>(L1WorldMap.java:46)
server_1  | 	at l1j.server.server.model.map.L1WorldMap.getInstance(L1WorldMap.java:36)
server_1  | 	at l1j.server.server.GameServerThread.<init>(GameServerThread.java:177)
server_1  | 	at l1j.server.server.GameServerThread.getInstance(GameServerThread.java:95)
server_1  | 	at l1j.server.server.GameServer.initialize(GameServer.java:139)
server_1  | 	at l1j.server.Server.main(Server.java:73)
```

**Comment by montanaflynn** [comment]
This was actually a database problem, somehow the migration didn't complete.

**Comment by zxcdesinger** [comment]
Hello how did you solve this issues? and you can upload your database<3
